version: '3.8'

services:
  bookich-db:
    image: postgres:15-alpine
    container_name: bookich_db
    environment:
      - POSTGRES_DB=bookich_database
      - POSTGRES_USER=bookich_user
      - POSTGRES_PASSWORD=ilnur@089
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bookich-app:
    build: .
    container_name: bookich_app
    ports:
      - "8080:8080"
    depends_on:
      - bookich-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookich-db:5432/bookich_database?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: bookich_user
      SPRING_DATASOURCE_PASSWORD: ilnur@089

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:9000

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://host.docker.internal:9000/oauth2/jwks
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: